export const SWAGGER_API_ROOT = 'docs';
export const SWAGGER_API_NAME = 'CHALLENGE BACKEND VACANCY API';
export const SWAGGER_API_DESCRIPTION =
  'API IMPLEMENTING AS A RESPONSE AND SOLUTION TO THE CHALLENGE OF A JUNIOR BACKEND VACANCY.';
export const SWAGGER_API_CURRENT_VERSION = '1.0';
